### ISSUE TITLE
Backstage fails to start:  Error: Cannot find module './out/isolated_vm'

### ISSUE THREAD

**Issue by cmoulliard** [q-shift/backstage-plugins#4]
## Issue

```
yarn dev
yarn run v1.22.19
$ concurrently "yarn start" "yarn start-backend"
$ yarn workspace backend start
$ yarn workspace app start
$ backstage-cli package start
$ backstage-cli package start
[0] Loaded config from app-config.yaml
[0] <i> [webpack-dev-server] Project is running at:
[0] <i> [webpack-dev-server] Loopback: http://localhost:3000/, http://[::1]:3000/
[0] <i> [webpack-dev-server] Content not from webpack is served from '/Users/cmoullia/code/openshift/backstage-plugins/qshift-quarkus/packages/app/public' directory
[0] <i> [webpack-dev-server] 404s will fallback to '/index.html'
[0] <i> [webpack-dev-middleware] wait until bundle finished: /create
[1] node:internal/modules/cjs/loader:1048
[1]   const err = new Error(message);
[1]               ^
[1] 
[1] Error: Cannot find module './out/isolated_vm'
[1] Require stack:
[1] - /Users/cmoullia/code/openshift/backstage-plugins/qshift-quarkus/node_modules/isolated-vm/isolated-vm.js
[1] - /Users/cmoullia/code/openshift/backstage-plugins/qshift-quarkus/node_modules/@backstage/plugin-scaffolder-backend/dist/cjs/router-ca1e7c8a.cjs.js
[1] - /Users/cmoullia/code/openshift/backstage-plugins/qshift-quarkus/node_modules/@backstage/plugin-scaffolder-backend/dist/index.cjs.js
[1] - /Users/cmoullia/code/openshift/backstage-plugins/qshift-quarkus/packages/backend/src/plugins/scaffolder.ts
[1] - /Users/cmoullia/code/openshift/backstage-plugins/qshift-quarkus/packages/backend/src/index.ts
[1]     at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
[1]     at a._resolveFilename (/Users/cmoullia/code/openshift/backstage-plugins/qshift-quarkus/node_modules/tsx/dist/cjs/index.cjs:1:1729)
[1]     at Module._load (node:internal/modules/cjs/loader:901:27)
[1]     at Module.require (node:internal/modules/cjs/loader:1115:19)
[1]     at require (node:internal/modules/helpers:130:18)
[1]     at Object.<anonymous> (/Users/cmoullia/code/openshift/backstage-plugins/qshift-quarkus/node_modules/isolated-vm/isolated-vm.js:1:18)
[1]     at Module._compile (node:internal/modules/cjs/loader:1241:14)
[1]     at Object.S (/Users/cmoullia/code/openshift/backstage-plugins/qshift-quarkus/node_modules/tsx/dist/cjs/index.cjs:1:1292)
[1]     at Module.load (node:internal/modules/cjs/loader:1091:32)
[1]     at Module._load (node:internal/modules/cjs/loader:938:12)
[1]     at Module.require (node:internal/modules/cjs/loader:1115:19)
[1]     at require (node:internal/modules/helpers:130:18)
[1]     at Object.<anonymous> (/Users/cmoullia/code/openshift/backstage-plugins/qshift-quarkus/node_modules/@backstage/plugin-scaffolder-backend/dist/cjs/router-ca1e7c8a.cjs.js:21:18)
[1]     at Module._compile (node:internal/modules/cjs/loader:1241:14)
[1]     at Object.S (/Users/cmoullia/code/openshift/backstage-plugins/qshift-quarkus/node_modules/tsx/dist/cjs/index.cjs:1:1292)
[1]     at Module.load (node:internal/modules/cjs/loader:1091:32) {
[1]   code: 'MODULE_NOT_FOUND',
[1]   requireStack: [
[1]     '/Users/cmoullia/code/openshift/backstage-plugins/qshift-quarkus/node_modules/isolated-vm/isolated-vm.js',
[1]     '/Users/cmoullia/code/openshift/backstage-plugins/qshift-quarkus/node_modules/@backstage/plugin-scaffolder-backend/dist/cjs/router-ca1e7c8a.cjs.js',
[1]     '/Users/cmoullia/code/openshift/backstage-plugins/qshift-quarkus/node_modules/@backstage/plugin-scaffolder-backend/dist/index.cjs.js',
[1]     '/Users/cmoullia/code/openshift/backstage-plugins/qshift-quarkus/packages/backend/src/plugins/scaffolder.ts',
[1]     '/Users/cmoullia/code/openshift/backstage-plugins/qshift-quarkus/packages/backend/src/index.ts'
[1]   ]
[1] }
[1] 
[1] Node.js v20.9.0
[0] webpack compiled successfully
```

**Comment by cmoulliard** [comment]
Fixed. My local python3 environment was broken. I had to reinstall it using homebrew.
